Add revision field into config + use it to fetch istio configmap
kiali/kiali pull request #3193
Opened 2020-09-09 14:01 UTC by xeviknal

Fixes https://github.com/kiali/kiali/issues/3187
Requires: https://github.com/kiali/kiali-operator/pull/126

When istio is installed using the canary upgrade feature [1], Kiali have errors in service details page. This is the following error:

![lclKJB6](https://user-images.githubusercontent.com/613814/92607458-70e03b80-f2b4-11ea-87b1-05a5050ef5eb.png)

In order to indicate the installation revision, there is now available the following setting:

```yaml
external_services:
  istio:
    revision: canary
```
In case istio is installed without revision, then this revision setting should be `""` (or left it empty).

[1] https://istio.io/latest/docs/setup/upgrade/

2020-09-09 14:14 UTC, jmazzitelli submitted a review, later dismissed
code looks good.

2020-09-10 11:16 UTC, hhovsepy approved these changes
Verified, regression tested on istio upstream.

2020-09-10 12:56 UTC, lucasponce requested changes
Would you mind to rebase with master ?

This PR has some problems with UI master due lack of updates there, if you don't mind, I can test the whole cycle after rebased.

2020-09-10 15:03 UTC, lucasponce approved these changes
Regression test passed.
After rebase, PR is synced with UI.

2020-09-10 15:03 UTC, merged