Add principals into security appender
kiali/kiali pull request #3208
Opened 2020-09-14 23:32 UTC by lucasponce

@jshaughn: I've started to add the discussed changes for https://github.com/kiali/kiali/issues/2924 into the security appender.

I think these changes make sense but perhaps I'm less familiar with the structure.

Feel free to comment.

Note: it's not yet finished, tests and other checks are missing.

2020-09-14 23:56 UTC, jshaughn requested changes
I think this is the right way to do it, piggybacking on the security appender is nice.  I think it's perfectly reasonable to require the 'Security' Display option.  Note that opetions can be automatically enabled if and when that makes sense.  For example, if you type 'has mtls' into graph find you'll see that the security option gets enabled automagically.

A few minor comments about alphabetizing, a more major comment about removing the redundancy, but the main blocker is that you need to add to the test code.  If you need help let me know, you could progress with the main feature and when I have time I can offer a sub-pr.

2020-09-14 23:56 UTC, jshaughn commented on graph/config/cytoscape/cytoscape.go
> +	SourcePrincipal string       	`json:"sourcePrincipal,omitempty"`
Just needs format a short comments for each new field.  For bonus points alphabetize below // App Fields.

2020-09-14 23:56 UTC, jshaughn commented on graph/config/cytoscape/cytoscape.go
> +			}
Alphabetize (just flip them)

2020-09-14 23:56 UTC, jshaughn commented on graph/meta.go
> +	DestPrincipal   MetadataKey = "destPrincipal"
Alphabetize

2020-09-14 23:56 UTC, jshaughn commented on graph/telemetry/istio/appender/security_policy.go
> +	a.populatePrincipalMap(principalMap, &inVector)
Not sure you really need to do all of this separately, I'd suggest maybe just working this into the existing 'populate' and 'apply' and not have to walk through everything twice.  If you are worried about getting the feature in then this is fine for now and I'll probably refactor it later.

2020-09-15 00:11 UTC, lucasponce commented
Thanks @jshaughn, let me know how it looks like now.

2020-09-15 02:20 UTC, jshaughn approved these changes
Seems fine, maybe we can optimize a little more but certainly looks good enough to progress.

2020-09-15 06:45 UTC, merged