Workload Logs: Avoid business package name shadowing by using criterias
kiali/kiali pull request #3358
Opened 2020-10-27 14:57 UTC by cfcosta

This is a followup to #3331, using criterias to generate the options so we don't have to access the underlying types directly, and thus avoiding the `business` package to conflict with the `business` variable we use for the business layer.

2020-10-27 17:44 UTC, jshaughn requested changes
@cfcosta One small change andthen I can test it out.

2020-10-27 17:44 UTC, jshaughn commented on handlers/workloads.go
>  	businesspkg "github.com/kiali/kiali/business"
We can remove this prefix.

2020-10-27 17:46 UTC, cfcosta commented on handlers/workloads.go
>  	businesspkg "github.com/kiali/kiali/business"
done

2020-10-27 18:23 UTC, jshaughn submitted a review, later dismissed
LGTM, I think this should satisfy Lucas' want.

2020-10-28 08:21 UTC, lucasponce commented on handlers/workloads.go
> +	opts := business.Workload.BuildLogOptionsCriteria()
This is good.
But I wonder why wouldn't you like to move the parsing into this method instead to use it just like an initialization.

Look this example in the other handler:

```
criteria := business.ParseIstioConfigCriteria(namespace, objects, labelSelector, workloadSelector)
```

The paremeters are passed into this `ParseIstioConfigCriteria` and then the criteria is used for the business method.
If the parse error fails you can send a back a 500 or 400 (depends if you want to notify user that parameters were incorrect).

Benefit of this is that handler doesn't touch business logic, only invoking business hence you can save to bring the meta_v1 package.

It's just style, this code works, but in rest of the handlers that's the style we used.

In any case this solves the previous request (thank you!).

2020-10-30 19:14 UTC, jshaughn approved these changes
I think this satisfies what @lucasponce is asking for.   Handler now knows only about request/respone handling and business package understands how to handle/parse the query param values and populate the criteria.

2020-10-30 19:17 UTC, jshaughn commented
I tested this and assuming travis also passes, and because this is just a small refactor to a PR already passed by QE, I think it is OK to merge as-is.

2020-10-31 13:12 UTC, cfcosta commented
@jshaughn tests are ok (travis did take forever to run though), need an approval :)

2020-11-02 02:46 UTC, jshaughn approved these changes
LGTM

2020-11-02 03:32 UTC, merged