Jaeger client: switch to gRPC/protobuf
kiali/kiali pull request #3601
Opened 2021-01-19 16:42 UTC by jotak

Fixes https://github.com/kiali/kiali/issues/3514

2021-01-19 16:44 UTC, jotak commented
WIP: proof of concept looks OK, I have a working GRPC-based connection with Jaeger to fetch traces.
Now it needs to be generalized in our jaeger calls, remove the old http client / clean up code.
And measure performance.

2021-01-20 12:21 UTC, jotak commented
Pretty much done, but I totally haven't tested yet the authentication stuff. Since it's the first time we use grpc in Kiali, the related code hasn't been tested at all yet. (To do before merging.)

Next step is also to run some perf tests.

2021-01-20 14:58 UTC, jotak commented
I've done some comparisons that don't really show any performance gain...
(and yes that's a bit disappointing)

2021-01-21 10:47 UTC, jotak commented
So, I could finally get some better numbers:

![Capture d’écran de 2021-01-21 11-16-38](https://user-images.githubusercontent.com/2153442/105340320-02a27280-5bde-11eb-8f47-49896c2df444.png)

The test runs queries continuously for 2 minutes with sleeps between queries. The query is crafted to be reasonably fast on the jaeger side (heavy queries would make storage latency preponderant against kiali-jaeger latency, hence hiding any improvement here).

So, while the p99 latency is quite comparable (~250ms on master versus ~230ms on grpc), the average latency is really better (~140ms on master versus ~80ms on grpc). Which allows a better throughput too (2.2ops versus 2.9ops - there's a sleep time between queries, throughput could be much higher)

2021-01-21 11:42 UTC, lucasponce commented
> So, I could finally get some better numbers:

Good :), but not really a concern.

One thing to take into consideration is that grpc introduces a strong dependency in the protobuf or client-library used by Jaeger.
I'll also check with @FilipB that this could works ok with upstream and potential versions packaged in downstream to avoid this situation forces to import different versions on each environment (probably not, just thinking loud potential areas to check).

Also, the Oauth config on downstream for Jaeger service is something that probably it would require a closer testing.

2021-01-22 14:44 UTC, FilipB commented
Tried with istio 1.8.2 and bookinfo. Following error thrown on Services->bookinfo->details->Traces page:
`jaeger GRPC client error: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: tls: first record does not look like a TLS handshake"`

Tried with both `values.meshConfig.enableAutoMtls=false` and `values.meshConfig.enableAutoMtls=true` with the same result.

2021-01-27 08:39 UTC, lucasponce commented
Thanks @FilipB, feel free to add a revision as well, just to prevent that we don't merge it without notice and we don't skip it.

2021-01-27 09:42 UTC, jotak commented
@FilipB , I suspect you were using a jaeger install serving on https, right? Mine is http and I've found a bug indeed with https (fixed now). If not, then it was something else.
By the way, mesh TLS having no effect here is totally expected (unless you have jaeger deployed as part of the mesh)

2021-02-01 12:51 UTC, FilipB requested changes
I still see the `jaeger GRPC client error: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: tls: first record does not look like a TLS handshake"` error even with the `86bcccf` commit.

Jaeger is installed as add-on via - https://github.com/kiali/kiali/blob/master/hack/istio/install-istio-via-istioctl.sh#L298

2021-02-03 06:51 UTC, jotak commented
Hey @FilipB ,
Can you check if you get the same in master and it is actually a regression? Isn't it a misconfiguration you have?
Even with the hack script I get jaeger deployed as http/port 80 so you should have in your Kiali CR / CM something like `in_cluster_url: http://tracing.istio-system/jaeger` (no https)

2021-02-04 13:15 UTC, jotak commented
(squashed and rebased)

2021-02-05 08:00 UTC, FilipB commented
Not ideal scenario to compare perf results but still it's visible that gRPC (top of the picture) is slightly better. Looking at avg,GetWorkloadTraces it oscillates around 40ms for gRPC (this PR) and around 50ms for master.
Jaeger and kiali pods were running on different OCP worker nodes.

![metrics](https://user-images.githubusercontent.com/328182/107004790-1679d700-678f-11eb-9a2f-abe4109ec3c0.png)

2021-02-05 12:58 UTC, FilipB commented
Tested this PR with OpenShift Service Mesh 2.0.1. It was necessary to remove the '-v 3' parameter from kiali container starting command in kiali deployment yaml (spec.template.spec.containers.command) to avoid following error during kiali pod startup:
```
flag provided but not defined: -v
Usage of /opt/kiali/kiali:
  -config string
    	Path to the YAML configuration file. If not specified, environment variables will be used for configuration.
```

Kiali pod was started but traces failed to be shown with following error:
`GetTraceDetail, Jaeger GRPC client error: rpc error: code = Unavailable desc = connection closed`

Kiali log does not show any error, only following info:
`2021-02-05T12:46:57Z INF Jaeger GRPC client info: address=jaeger-query.istio-system.svc:443, auth={/kiali-cabundle/service-ca.crt false f+fdlQbTcQ+EFDMrHm6DswMIvKkQkG33nL8uUwehHWNvSfYXPWCh3p8PFUPCO7Te0IItrEEqbpyHSTAB+TKwLBzI9gA21xcGe/VKQFJyAhDB59DRFNxtZ6pVIXMx1UIGJb9bWaQY47OG4fDnBDnkRG9vupA+gCcjag6sZHHKGaZMXoscJCOpzrSqz5BWf8ByASSyx18gzJ5uxf3deXJL9V4YGNz7M/xCaaanGLrOFGEaObvoVlrSa/iq0uc7GvBlnsoXGjFVmtaWitwYSfPVUA0yXQ1I8l9SH9Z0czaJXOzHA4gyKRujLEw0czgHXBkFLZ4qMHdOUvcSX615FBrx  basic false internal}`

2021-02-10 15:57 UTC, jotak commented
At the moment, I haven't found a solution to fix this issue with ossm. I've opened an issue on oauth-proxy, I think it doesn't support grpc (to be confirmed).

In any case I think we should either implement an hybrid solution where both http and grpc clients are possible (switchable from config), or leav it aside for a moment. I'm not super confident that switching to a grpc-only solution would work in every situation, every kind of customer setup, so I would prefer a more conservative approach with the two implementations living side by side. A question would remain: which one would be enable by default? I'd say the grpc one, in order to get as many feedbacks as possible.

2021-02-10 15:59 UTC, jotak commented
tracking issue on oauth-proxy: https://github.com/openshift/oauth-proxy/issues/205

2021-02-10 16:27 UTC, jshaughn commented
>  A question would remain: which one would be enable by default? I'd say the grpc one, in order to get as many feedbacks as possible.

I'd say maybe GRPC upstream and HTTP downstream, if possible.

2021-02-10 16:34 UTC, jmazzitelli commented
> I'd say maybe GRPC upstream and HTTP downstream, if possible.

We don't have build procedures in place today that would be able to have different configurations built into upstream vs. downstream binaries/configs. But there are two ways we could do this:

1) Have the OSSM Operator create the necessary config setting in the Kiali CR that it creates (thus the OSSM Operator will tell Kiali what setting it should use).

or

2) Have one default setting if the Kiali Operator sees it is installing Kiali in an OpenShift (or even a Maistra) environment, and a different setting otherwise (we already do this kind of thing for other settings - spec.auth.strategy for one).

2021-02-10 16:34 UTC, jotak commented
> 
> I'd say maybe GRPC upstream and HTTP downstream, if possible.

Yes, since that would be configurable, we can push a config specific to ossm

2021-02-12 12:19 UTC, jotak commented
Rebased + added some code comments about untested GRPC client with secured communication. I will add a faq entry to kiali.io too.

2021-02-12 16:18 UTC, FilipB approved these changes
Tested following:
- grpc is disabled by default for service mesh and enabled for istio
- use_grpc flag works as expected
- grpc client (use_grpc=true) is not working for service mesh (which is expected - ERR GetAppTraces, Jaeger GRPC client error: rpc error: code = Unavailable desc = connection closed)
- it works fine for both use_grpc=true/false in istio
- tested with both all-in-one and production-elasticsearch jaeger templates

2021-02-15 12:52 UTC, merged