Assume a connectivity issue on Prometheus API failures
kiali/kiali pull request #4026
Opened 2021-05-18 12:40 UTC by jshaughn

Assume a connectivity issue on Prometheus API failures. A CX issue is fairly typical, an application error is very unlikely.  This stops stack traces returned to the user on a prom connectivity problem.

Fixes https://github.com/kiali/kiali/issues/4014

2021-05-18 13:20 UTC, lucasponce requested changes
I guess this is not feature complete if we want to point that, this is only covering the graph feature but not health nor metrics:

![image](https://user-images.githubusercontent.com/1662329/118658041-4f910100-b7ec-11eb-9cf7-8389f9b184d0.png)

Otherwise some endpoint may report an 503 and others a 500 for same scenario: Prometheus connectivity.

(I'm fine with the change, just requesting to use the same code in those endpoints, too).

2021-05-18 14:38 UTC, jshaughn commented
> ...this is only covering the graph feature but not health nor metrics:

@lucasponce OK, I wasn't sure if we cared about it so in the initial offering I responded specifically to the reported problem.  The error handling is not the same across the subsystems, so it will take some specific work in each place.  I'll follow up with another commit.

2021-05-18 18:26 UTC, jshaughn commented
@lucasponce OK, failed calls to Metrics will now also be returning 503s.

2021-05-21 11:11 UTC, lucasponce commented
I guess the health endpoints are still sending a 500
![image](https://user-images.githubusercontent.com/1662329/119128388-e43a6f80-ba35-11eb-94d3-2acabae0f901.png)

Probably it can be fix it in the kiali/handlers/errors.go

2021-05-25 01:05 UTC, jshaughn commented
@lucasponce OK, I think I plugged the remaining holes.  I'm seeing only 503s with Prom at 0 pods.

2021-05-25 12:23 UTC, lucasponce approved these changes
The 500 errors are moved into 503.
I see a couple of imrprovements in the UI as the health promises throw an error that is not properly caught in the AlertCenter, but that's ok, I think it's out of the scope of this PR.

2021-05-25 12:53 UTC, jshaughn commented
@mattmahoneyrh This is more of an internal change but if you want to perform QE you can cycle down prometheus to 0 pods and ensure that any requests that fail due to prometheus return 503 (ServiceUnavailable) as opposed to 500 (ApplicationError).

2021-05-25 14:45 UTC, nrfox commented
This is probably out of scope for this change since this centers around prometheus and the responses returned by prom connectivity but should the api be returning a stack trace at all to the client? It seems that was part of the concern in #4014 and it just so happened that prom connectivity was the cause of the error and the stack trace to be included in the response. Perhaps the api can log the stack [here](https://github.com/kiali/kiali/blob/5bcdd2f372ff2fcca4746e321bd9e93e677e1b0c/handlers/graph.go#L85-L90) when recovering from a panic in the graph but exclude it from the response.

2021-05-25 15:33 UTC, jshaughn commented
>  but should the api be returning a stack trace at all to the client?

I have no idea whether a stack trace is a bad thing to return to the client.  I know it was brought up as a, I guess, a potential security concern in the original issue, but up to this point no one has complained and it has made it easier to diagnose a couple of bugs by easily asking the user for a trace.  So today we return it in the response and we log it, but here's the thing, the logged trace is just as accessible to a client, as we already have a way of displaying kiali pod logs via the workload detail (or an API call).

So,I guess my vote is to leave it as is.

2021-05-26 17:32 UTC, pbajjuri20 commented
Before PR:

![bfd](https://user-images.githubusercontent.com/55099523/119705439-bf277180-be26-11eb-8804-f7c2df1b277a.png)

After PR:

![bbd](https://user-images.githubusercontent.com/55099523/119705489-ccdcf700-be26-11eb-910f-7a4ae6fe7bca.png)

2021-05-26 17:32 UTC, pbajjuri20 approved these changes

2021-05-26 18:35 UTC, merged