Add additional kiali scenarios to node metadata
kiali/kiali pull request #4043
Opened 2021-05-24 14:02 UTC by nrfox

Adds all supported kiali traffic wizard scenarios to the service node metadata if they have the `kiali_wizard` label.

Relates to: #1477

2021-05-25 19:00 UTC, jshaughn requested changes
A couple of minor changes

2021-05-25 20:13 UTC, nrfox commented on graph/telemetry/istio/appender/istio_details.go
> +				// Check if the VS also has one of the Kiali scenarios created by the wizard.
That's how it works today. There's only a single `kiali_wizard` label that gets set on the VS object. Its value is whatever wizard was used to create the object (`request_routing`, `fault_injection`...). The front-end prevents you from creating another VS/DR object when there's an existing one. You can only update or delete.

2021-05-25 20:15 UTC, nrfox commented on graph/types.go
> +	RequestTimeoutsLabel    string = "request_timeouts"
I'm not sure what else would need these server side other than the graph in order to add the node badges.

2021-05-27 15:44 UTC, lucasponce commented on graph/telemetry/istio/appender/istio_details.go
> +				}
Yes, I think we have two situations:
- Istio resources created outside of Kiali won't have the label, so those can be treated as previously.
- Kiali generated resources may no need the additional VS (or no need to duplicate it in the graph).

But as I commented, the goal should be that any Istio VS config can fall at least in the RequestRouting scenario (not yet supported but planned).

2021-06-02 10:03 UTC, lucasponce approved these changes

2021-06-03 19:00 UTC, pbajjuri20 approved these changes
Tested and passed on Kiali-UI 1.36.0 (1325f3d75900f572299231f22872d9f028eaa61e)

2021-06-03 19:45 UTC, merged