Added cross-namespace validation support on validation KIA0202 for exportTo field of ServiceEntry
kiali/kiali pull request #4358
Opened 2021-09-16 09:19 UTC by hhovsepy

RFE https://github.com/kiali/kiali/issues/3061
Subtask : https://github.com/kiali/kiali/issues/4316

On validation message "KIA0202 This host has no matching entry in the service registry (service, workload or service entries)" is now added a support of cross-namespace checking of ServiceEntries.

So create a ServiceEntry:
![Screenshot from 2021-09-16 10-46-24](https://user-images.githubusercontent.com/604313/133585557-f9187a59-8f81-4a07-9892-eded744d719d.png)

Before when linking from DR to that SE which was in different namespace, it was showing an error:
![Screenshot from 2021-09-16 08-40-52](https://user-images.githubusercontent.com/604313/133585678-222e2317-d7b1-46f5-8a0b-f47d2646b52a.png)

Now error on host is not shown:
![Screenshot from 2021-09-16 10-48-11](https://user-images.githubusercontent.com/604313/133585861-9673da97-1327-4f2e-85d5-8f4903e42fec.png)

But try to export SE into local namespace only:
![Screenshot from 2021-09-16 11-17-51](https://user-images.githubusercontent.com/604313/133585971-5548f781-a761-4b25-a0ac-b94805de9ae4.png)

The error is shown, as SE is not available into DR's namespace:
![Screenshot from 2021-09-16 11-18-46](https://user-images.githubusercontent.com/604313/133586164-a63e9ce4-c23f-4010-8858-ebea76b3f972.png)
![Screenshot from 2021-09-16 11-19-04](https://user-images.githubusercontent.com/604313/133586167-1b5511e2-72b3-48bc-847e-68196a6475c9.png)

2021-09-17 13:23 UTC, lucasponce commented
I'm seeing something strange in the validations.
I'm testing "master" just to test the scenario before to test it on this branch.

I have this scenario:

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: edition-cnn-com
  namespace: alpha
spec:
  hosts:
    - edition.cnn.com
  ports:
    - number: 80
      name: http-port
      protocol: HTTP
      targetPort: 443
    - number: 443
      name: https-port
      protocol: HTTPS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: edition-cnn-com
  namespace: beta
spec:
  host: edition.cnn.com
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 80
        tls:
          mode: SIMPLE # initiates HTTPS when accessing edition.cnn.com
```

But I get a KIA0202:
![image](https://user-images.githubusercontent.com/1662329/133789475-66957626-b833-40b8-bfa2-179793206db0.png)

I can see that the ServiceEntry is also included in the registry:
![image](https://user-images.githubusercontent.com/1662329/133789541-63a044c4-3259-4596-8665-cb46c3a4803e.png)

So I have the suspects that perhaps there is some regression introduced in the validations.

I'm commenting this because I'm going to review this potential regression in the context of this PR as well
(so it will take more time from my side, but I wanted to give some update to put in context).

2021-09-17 13:27 UTC, lucasponce commented
Ouch, please, don't take my previous comment.
It was a cached issue from my environment, once that the registry status is correct I saw the validation fixed.

Sorry for the noise.
![image](https://user-images.githubusercontent.com/1662329/133790211-c517237a-0924-44d4-9026-2c546bf0b90d.png)

2021-09-20 13:47 UTC, hhovsepy commented
This first scenario is the expected behaviour which should be in master. The error is shown as cross-namespace validation is not supported yes.

The purpose of this PR is to consider cross-namespace ServiceEntries while validation DestinationRule, and do not show error KIA0202 in these cases.

And the second behavior @lucasponce you are facing, I also see in master or testing clusters, not sure how this happens, somehow the ServiceEntries are cached. But when running master locally with cache off, then error KIA0202 is shown as expected.

2021-09-21 07:12 UTC, lucasponce commented
Ok, I guess we can move in several directions.
I suggest that we can consolidate this work, but I think I'm going to create an Epic describing how we can use the Istio registry to perform those validations and consolidate (and hopefully simplify) the validation logic for several conditions.

In that case, validations can save to pull kubernetes services, as the registry will give you all visibility of the cluster and probably some cross-validation logic can be simplified.

2021-09-21 09:39 UTC, hhovsepy commented
+1 on that, as the registry usage is for all other validations as well
> Ok, I guess we can move in several directions.
> I suggest that we can consolidate this work, but I think I'm going to create an Epic describing how we can use the Istio registry to perform those validations and consolidate (and hopefully simplify) the validation logic for several conditions.

2021-09-22 11:36 UTC, lucasponce approved these changes
LGTM
As commented, I collected my thoughts about how we can consolidate cross-namespace validation in a wider context using the Istio registry.
https://github.com/kiali/kiali/issues/4382

That will trigger more changes, but I think it's ok to consolidate these changes meanwhile we discuss the #4382 for future Sprints.

2021-09-23 12:05 UTC, prachiyadav requested changes
export SE into local namespace only but error is not shown, as SE is not available into DR's namespace

![Screenshot from 2021-09-23 17-32-00](https://user-images.githubusercontent.com/13483060/134503512-c915dad3-dd98-40f2-bc79-f5afba37faa5.png)
![Screenshot from 2021-09-23 17-15-47](https://user-images.githubusercontent.com/13483060/134503522-4b5906b6-8f5f-489f-ac59-03cb1a0471f3.png)

2021-09-23 12:10 UTC, hhovsepy commented
> export SE into local namespace only but error is not shown, as SE is not available into DR's namespace
It seems because of cache issue https://github.com/kiali/kiali/issues/4382
Can you please retest with cache disabled, or create a new SE with different name?

2021-09-23 12:23 UTC, prachiyadav approved these changes
Approving change as disabling the cache make this PR work.

![Screenshot from 2021-09-23 17-52-47](https://user-images.githubusercontent.com/13483060/134505989-1f1b4c4f-b00e-4a9d-a8c4-ec7e725ce834.png)

2021-09-23 15:35 UTC, merged