Kiali Istio dashboards incompatible with thanos-query
kiali/kiali pull request #4386
Opened 2021-09-22 12:28 UTC by aljesusg

Fix https://github.com/kiali/kiali/issues/4303

2021-09-22 13:19 UTC, jmazzitelli requested changes
comment from the issue:
> I'm going to create the PR with these proposed changes but I think as far as I know that this is not going to fix it.

If we don't think this is going to do anything, then we should not merge this. If it doesn't fix the problem, we should not add this "just to add it". We should look into things further and fix the issue and not add code that doesn't address the problem.

2021-09-22 13:21 UTC, jmazzitelli commented
I would set this PR to "draft" status, build the server with these changes, and ask for the person who reported the issue to test with that build and see if it does, indeed, address the issue.

2021-09-22 13:51 UTC, aljesusg commented
Totally agree, I am trying to test this in GCp but IAM is playing with me and I can’t write in bucket, but as you said maybe @vbergbauer can test it

2021-09-22 14:25 UTC, vbergbauer commented
@aljesusg : If you build a container image for me, I'll happily test it.
I know how to reproduce the problem on various clusters (KinD, GKE, OCP).

2021-09-22 15:22 UTC, aljesusg commented
Thanks @vbergbauer I pushed the image in quay.io/aljesusg/kiali:dev ...I am checking and I think it solves it

2021-09-22 15:29 UTC, jmazzitelli commented on config/config.go
> +type Thanos struct {
shouldn't we call this ThanosProxy just to remain consistent with the json name?

2021-09-22 15:39 UTC, jmazzitelli commented
I'm not sure if anything else has to change, but I will bring this up ... there is another place where prometheus config is in our configuration (this is Kiali CR's `spec.external_services.custom_dashboards`):

```
// CustomDashboardsConfig describes configuration specific to Custom Dashboards
type CustomDashboardsConfig struct {
	DiscoveryEnabled       string           `yaml:"discovery_enabled,omitempty"`
	DiscoveryAutoThreshold int              `yaml:"discovery_auto_threshold,omitempty"`
	Enabled                bool             `yaml:"enabled,omitempty"`
	IsCore                 bool             `yaml:"is_core,omitempty"`
	NamespaceLabel         string           `yaml:"namespace_label,omitempty"`
	Prometheus             PrometheusConfig `yaml:"prometheus,omitempty"`
}
```

Notice there is a PrometheusConfig here also (it defines the secondary Prometheus that Kiali can query for the custom dashboard metrics.) This means there can also be a ThanosProxy defined here for the secondary Prometheus. It is probably a no-op (i.e. if a user specifies a ThanosProxy here inside this `spec.external_services.custom_dashboards.prometheus.thanos_proxy` it will have no effect and be ignored).

I want to mention this in case we actually do need to do something here with ThanosProxy config when accessing Prometheus for custom dashboard metrics.

2021-09-22 15:52 UTC, aljesusg commented
Yes If this work correctly I'll do the changes

2021-09-23 13:06 UTC, jmazzitelli requested changes

2021-09-23 13:06 UTC, jmazzitelli commented on config/config.go
> +				}
This should fix the linter error that is causing the build to fail:
```suggestion
						Enabled: false,
					},
				},
```

2021-09-23 14:06 UTC, jmazzitelli commented
If this is good and will be merged, we'll need an operator PR.

* Add to example CR: https://github.com/kiali/kiali-operator/blob/v1.40.0/deploy/kiali/kiali_cr.yaml#L619
* Add defaults: https://github.com/kiali/kiali-operator/blob/v1.40.0/roles/default/kiali-deploy/defaults/main.yml#L178

2021-09-27 16:03 UTC, vbergbauer commented
Hi @aljesusg 
Sorry for the delay (busy week last week).
I tested quay.io/aljesusg/kiali:dev and it does resolve the issue with custom dashboards without resorting to my workaround.
Thank you.

2021-09-27 16:26 UTC, aljesusg commented
Great we can continue @jmazzitelli

2021-10-05 05:27 UTC, merged

2021-10-05 12:25 UTC, jshaughn commented
@aljesusg Same comment as in the sibling PR.