Gateways linked in VirtualServices are listed in ServiceLists Details column.
kiali/kiali pull request #4400
Opened 2021-09-30 18:25 UTC by hhovsepy

RFE https://github.com/kiali/kiali/issues/4326

When VirtualService have linked Gateways, then these Gateways are listed in Details column of ServiceLists page.
Also Services they can be filtered by Gateways.
Gateways can be linked for instance while creating Routing via Wizard.

![Screenshot from 2021-09-30 20-22-36](https://user-images.githubusercontent.com/604313/135510392-f015ac8d-f9ec-4daf-93d6-a2ccf9241f02.png)

2021-10-01 10:20 UTC, lucasponce requested changes
I think is missing also in the app view.
The app view links the istio references to the services and workloads that belongs to an app.

So, the service list looks correct:
![image](https://user-images.githubusercontent.com/1662329/135604169-da9a0e2c-9ff1-4cc2-a322-d97e2d2d762d.png)

But the app list is missing the gateway:
![image](https://user-images.githubusercontent.com/1662329/135604214-a95ea1e2-3d6f-4a80-94da-a334af6f9472.png)

Not a big change, just to apply same logic.

But I'm also thinking beyond, as the gateway is a "mix" type in the sense that is linked with VirtualServices, but it's also linked with Workloads.

Typically we assume that the "gateway" workload are the predefined in the control plane:
![image](https://user-images.githubusercontent.com/1662329/135604406-13b9a213-7170-43d4-88ed-ffe1bae32911.png)

But we know that users can define "gateway" workloads in other places as well, but perhaps this last comment we can address them once the https://github.com/kiali/kiali/pull/4389 is progressed to not introduce too many new conflicts as well :-).

2021-10-04 10:19 UTC, hhovsepy commented
@lucasponce thanks for review, have added for AppLists as well, also fixed IstioConfig link from Lists page.

2021-10-06 10:16 UTC, lucasponce requested changes
@hhovsepy I've found a minor cornercase/edge after I approved:
![image](https://user-images.githubusercontent.com/1662329/136184358-6d74fe7a-e553-4d38-a5d2-090fc2381968.png)

I think in the case of the apps it should check the duplicates.

2021-10-06 10:17 UTC, lucasponce approved these changes

2021-10-06 10:53 UTC, skondkar approved these changes
LGTM
Verified on Services and Applications list pages. Verified navigation of gateway links work and wrong gateway names in VirtualServices did not appear in the list pages.

![Screenshot-ServiceList](https://user-images.githubusercontent.com/6614472/136189403-ecf4a010-078d-4a2f-afac-4ef31dd751fc.png)

![Screenshot-AppList](https://user-images.githubusercontent.com/6614472/136189484-8cd94335-85fc-462a-a077-bd66e383fcbe.png)

2021-10-06 12:21 UTC, merged