Global sidecar validation using the root namespace
kiali/kiali pull request #4470
Opened 2021-11-03 15:53 UTC by leandroberetta

This PR updates the global sidecar validation to honor the root namespace instead of the istio namespace.

Depends on #4465 

Fixes #4449

In the following example, the global validation applies to the Sidecar created in istio-config namespace (the root namespace).

![root_namespace_sidecar](https://user-images.githubusercontent.com/1286393/140095407-fbe83a46-9e70-4d1f-96b1-c1c2a99513ee.png)

2021-11-11 16:48 UTC, xeviknal approved these changes
LGTM!

2021-11-11 18:50 UTC, leandroberetta commented
The steps to test this are the following:

1. Configure Kiali to a different root namespace, for example "istio-config", this can be done via the CR:

```yaml
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:     
  name: kiali  
spec:
  external_services:    
    istio:
      root_namespace: istio-config
```

2. Wait for the operator to update Kiali configmap 

3. Create the following global Sidecar resource in istio-config namespace:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: default
  namespace: istio-config  
spec:
  workloadSelector:
    labels:
      app: ratings
  egress:
  - hosts:
    - "./*"
    - "istio-system/*"
```

4. Expect to see the following warnings in validations:
 
![root_namespace_sidecar](https://user-images.githubusercontent.com/1286393/141352773-dbf5c48c-f74c-4db7-9335-517caf1f1864.png)

2021-11-17 14:44 UTC, prachiyadav requested changes
This PR works when manually adding "istio-config" namespace to accessible namespace. Otherwise with default configuration it is not working.

2021-11-17 15:08 UTC, jmazzitelli commented
> This PR works when manually adding "istio-config" namespace to accessible namespace. Otherwise with default configuration it is not working.

Sounds like if istio.root_namespace is defined and not empty string AND accessible namespaces is not `['**']` then that root namespace needs to be added to the accessible_namespaces.

We do something similar with the deployment namespace in the operator and server helm chart, IIRC. Just need to do the same thing for root_namespace.

2021-11-17 15:16 UTC, leandroberetta commented
> > This PR works when manually adding "istio-config" namespace to accessible namespace. Otherwise with default configuration it is not working.
> 
> Sounds like if istio.root_namespace is defined and not empty string AND accessible namespaces is not `['**']` then that root namespace needs to be added to the accessible_namespaces.
> 
> We do something similar with the deployment namespace in the operator and server helm chart, IIRC. Just need to do the same thing for root_namespace.

@jmazzitelli thanks, yes, it's the same issue we got here: https://github.com/kiali/kiali/pull/4490

I will do that.

2021-11-18 16:59 UTC, leandroberetta commented
@prachiyadav can you try again this with the latest change on the operator (in master branch)?.

Now the root namespace should be included in the accessible_namespaces attribute.

2021-12-01 11:02 UTC, prachiyadav approved these changes

2021-12-01 13:11 UTC, merged

2021-12-03 12:56 UTC, prachiyadav commented
Test case >> SWSQE-2172