fix(metrics): add restrictions to queries
kiali/kiali pull request #4631
Opened 2021-12-24 17:02 UTC by Xunzhuo

add some restrictions to queries

2021-12-26 14:21 UTC, jmazzitelli commented
In all of these PRs you are creating, can you add more/better descriptions explaining (a) what is broken or missing and (b) what the new code is doing to fix it?

Right now, some of these just have code without any comments in the code, so it is hard to judge what you are doing in all of these code submissions.

2021-12-26 14:28 UTC, Xunzhuo commented
@jmazzitelli OK, I will update the descriptions.

2022-01-11 16:38 UTC, jshaughn requested changes
It's weird, but for this PR github is not allowing me to make inline comments.  So, unfortunately, I will have to do it all in one comment.

> the default value for requestProtocol is not all protocols

Are you sure this is true?  This is basically a filter, so when not supplied there is no filtering on protocol.   So, for example, if the metrics are coming from istio_requests_total, it could include HTTP and gRPC.

> when getting query of rateInterval , we did not check it formats, just take any values which are not "", which should be formated like 10s, 5m, 3h, 1h20s...

Are you sure Prometheus doesn't already validate the parameter and return an error if necessary?

> when getting query of queryTime duration and step , we do not check it if it is < 0, just take values which are not "".

Not sure this check is necessary but, if you leave it in, then you need to update the message below because it may no longer just be a parsing error. (same comment for the second occurrence)

Although your contributions are appreciated, In general I'd discourage code changes in mature projects, where there hasn't been a reported issue.  Any code change can have unexpected consequences.  I would encourage you to work on reported issues from the kiali issue backlog.

2022-01-11 17:18 UTC, Xunzhuo commented
Sure it is OK for this is a PR before I started a discussion about assigning issues. I could close this. Thanks @jshaughn For now, all PRs before assigning issues have been merged or closed. I will work on issues to submit feature PRs.

2022-01-11 17:18 UTC, closed without merging