fix: update healthz apis
kiali/kiali pull request #4634
Opened 2021-12-26 14:39 UTC by Xunzhuo

** Describe the change **

update healthz APIs docs: from `/api/healthz` to `/healthz`

** Issue reference **

fix https://github.com/kiali/kiali/pull/4632

** Backwards incompatible? **

- Is your change introducing backwards incompatible changes? Yes

_describe the changes if appropriate_

** Documentation **

* Does your contribution contain user-visible changes like e.g. new or changed configuration settings?
If so, please also update README.adoc

2021-12-26 14:41 UTC, Xunzhuo commented
cc @jmazzitelli , I start a new PR to update healthz api. But I do not know if there is a way to fix it in swagger for there is a base url `/api`.

2021-12-26 16:39 UTC, jmazzitelli approved these changes

2022-01-04 11:22 UTC, lucasponce commented
This PR may have a problem, as it would be re-created every time that swagger is generated.
So I guess it could be better to address this on the swagger side.
One way could be to not use the "basePath" in the "swagger.json" and let the handlers to take the "/api" there as there will be endpoints that won't use that prefix.

2022-01-04 11:24 UTC, lucasponce requested changes
I don't think it makes sense to modify the .md as these changes will be recreated.
I suggest investigating to add these changes in the swagger source ("swagger.json" or "doc.go" resources, or any other comment in the "routes.go")

2022-01-10 07:57 UTC, lucasponce commented
Closing this one, the "kiali_api.md" resource is auto-generated from the "swagger.json":
![image](https://user-images.githubusercontent.com/1662329/148733610-d40a6115-f411-478e-88db-7fb5e6a14d6b.png)

So, any change should be provided from the .json definition.

2022-01-10 07:57 UTC, closed without merging