feat: support config custom labels when scraping metrics
kiali/kiali pull request #4732
Opened 2022-02-15 04:15 UTC by Xunzhuo

Signed-off-by: Xunzhuo <mixdeers@gmail.com>

**Describe the change**

support config custom labels when scraping metrics

config like below:

``` yaml
  prometheus:
    url: "http://127.0.0.1:9090"
    thanos_proxy:
      enabled: true
      retention_period: "7d"
      scrape_interval: "30s"
    custom_labels:
      mesh: "meshID"
      cluster: "clusterID"
```

config key and values of custom labels.

**Issue reference**

https://github.com/kiali/kiali/issues/4664

**Backwards incompatible?**

No

**Documentation**

* Does your contribution contain user-visible changes like e.g. new or changed configuration settings?

Yes, need some changes in CR reference.

2022-02-15 13:15 UTC, jmazzitelli requested changes
Just gave this a quick glance, but found a flaw in the way the config is interpreted.

Two other things in addition to my code comment:

1. What does it mean to give custom labels to the custom dashboards prometheus config? Are these even used? If they are to be used, I don't see any new code in this PR that uses them. Code related to custom dashboard prometheus queries should be modified, too.
2. This is proposing new config to the Kiali CR which requires additional work over in the operator repo. Please see the documentation on what needs to be done: https://github.com/kiali/kiali-operator/blob/master/DEVELOPING.adoc#are-you-altering-a-kiali-server-configuration-setting

2022-02-15 13:15 UTC, jmazzitelli commented on graph/telemetry/istio/istio.go
> +		}
We don't want to do this. Here you are mixing the custom dashboards prometheus config with the regular prometheus config. The custom dashboards prometheus config is supposed to be isolated/separate from the "regular" prometheus config - the point being that the custom dashboards prometheus config points to a completely separate Prometheus instance than that of the Istio Prometheus. So one config should not assume the other - they are separate.

For details, see the kiali documentation:
* https://kiali.io/docs/configuration/custom-dashboard/#using-another-prometheus-instance
* https://kiali.io/docs/configuration/kialis.kiali.io/#.spec.external_services.custom_dashboards.prometheus

2022-02-15 18:10 UTC, jshaughn commented
As much as I appreciate the submissions, your PR's are too premature.  This one isn't even close to being complete.  We don't really have the time to repeatedly review PRs that are very incrementally improved.  You need to better understand what you are doing before submitting PRs.  Please look fully at the code-base, and ask questions, before submitting a PR.  I don't think the discussion was even complete in the associated issue.  I had left it with a question about multi-tenancy.

2022-02-15 18:15 UTC, jshaughn requested changes
@Xunzhuo I think maybe I should generate PRs for this and you could use this as an exercise to review code as opposed to submit code, and in the process perhaps learn more about the various touch points.

To be clear, the idea you have here, and what is in this PR, I think is reasonable.

2022-02-23 14:28 UTC, jshaughn commented
Hi @Xunzhuo , I think this original PR can be closed in favor of https://github.com/kiali/kiali/pull/4739.

2022-02-23 14:38 UTC, closed without merging

2022-02-23 14:39 UTC, Xunzhuo commented
> Hi @Xunzhuo , I think this original PR can be closed in favor of https://github.com/kiali/kiali/pull/4739.
> 
> 

thanks @jshaughn for helping me complete this PR, learned a lot!

2022-02-23 17:24 UTC, jshaughn commented
No problem @Xunzhuo , thank you for your continued contributions to Kiali.  The next step in the process will be for QE to approve the https://github.com/kiali/kiali/pull/4739 PR, that will likely happen next week, and so I would expect this feature to be in Kiali 1.48.  Until then, please feel free to use/test the PRs.