Kiali UI and Kiali Server can point to a single commit
kiali/kiali pull request #4903
Opened 2022-04-05 07:25 UTC by aljesusg

Fix https://github.com/kiali/kiali/issues/4895

![Screenshot from 2022-04-05 09-24-45](https://user-images.githubusercontent.com/3019213/161700766-7b0dcaca-3700-44f4-ba94-49d4a2020cc7.png)

# Changes in /api/status

- Removed **Kiali console version**
- Rename ~~**Kiali core version**~~ to **Kiali version**
- Rename ~~**Kiali core commit hash**~~ to **Kiali commit hash**

# Before /api/status

```json
{
  "status": {
    "Kiali console version": "unknown",
    "Kiali container version": "v1.49.0-SNAPSHOT",
    "Kiali core commit hash": "4f71e03c078592c10aee8a8deb48c4c066feea1a",
    "Kiali core version": "v1.49.0-SNAPSHOT",
    "Kiali state": "running"
  },
  "externalServices": [
    {
      "name": "Kubernetes",
      "version": "v1.21.2"
    },
    {
      "name": "Grafana"
    },
    {
      "name": "Jaeger"
    }
  ],
  "warningMessages": [
    "failed to get mesh version, please check if url_service_version is configured correctly."
  ],
  "istioEnvironment": {
    "isMaistra": false
  }
}
``````json
{
  "status": {
    "Kiali console version": "unknown",
    "Kiali container version": "v1.49.0-SNAPSHOT",
    "Kiali core commit hash": "4f71e03c078592c10aee8a8deb48c4c066feea1a",
    "Kiali core version": "v1.49.0-SNAPSHOT",
    "Kiali state": "running"
  },
  "externalServices": [
    {
      "name": "Kubernetes",
      "version": "v1.21.2"
    },
    {
      "name": "Grafana"
    },
    {
      "name": "Jaeger"
    }
  ],
  "warningMessages": [
    "failed to get mesh version, please check if url_service_version is configured correctly."
  ],
  "istioEnvironment": {
    "isMaistra": false
  }
}
```

# Now  /api/status

```json
{
  "status": {
    "Kiali console version": "unknown",
    "Kiali container version": "v1.49.0-SNAPSHOT",
    "Kiali core commit hash": "4f71e03c078592c10aee8a8deb48c4c066feea1a",
    "Kiali core version": "v1.49.0-SNAPSHOT",
    "Kiali state": "running"
  },
  "externalServices": [
    {
      "name": "Kubernetes",
      "version": "v1.21.2"
    },
    {
      "name": "Grafana"
    },
    {
      "name": "Jaeger"
    }
  ],
  "warningMessages": [
    "failed to get mesh version, please check if url_service_version is configured correctly."
  ],
  "istioEnvironment": {
    "isMaistra": false
  }
}
``````json
{
  "status": {
    "Kiali commit hash": "4f71e03c078592c10aee8a8deb48c4c066feea1a",
    "Kiali container version": "v1.49.0-SNAPSHOT",
    "Kiali state": "running",
    "Kiali version": "v1.49.0-SNAPSHOT"
  },
  "externalServices": [
    {
      "name": "Kubernetes",
      "version": "v1.21.2"
    },
    {
      "name": "Grafana"
    },
    {
      "name": "Jaeger"
    }
  ],
  "warningMessages": [
    "failed to get mesh version, please check if url_service_version is configured correctly."
  ],
  "istioEnvironment": {
    "isMaistra": false
  }
}
```

2022-04-05 09:32 UTC, lucasponce requested changes
I see the change in the /status, but not updated in the UI:
![image](https://user-images.githubusercontent.com/1662329/161724351-6d63c49f-c14a-4e19-ab3b-908e207ec7c3.png)

I'm testing with complete deployment in the cluster using:

```
#!/usr/bin/env bash
KIALI=$HOME/Projects/gopath/src/github.com/kiali/kiali
cd $KIALI

export CLUSTER_TYPE=minikube
export CLUSTER_REPO=localhost:5000
export CONSOLE_VERSION=local
export CONSOLE_LOCAL_DIR=$KIALI/frontend
export DORP=docker
export HELM_CHARTS_REPO=$HOME/Projects/repos/helm-charts
export HELM_CHARTS_REPO_PULL=false

make clean build cluster-push operator-create kiali-create
```

2022-04-05 10:06 UTC, aljesusg commented
O.O I saw a typo let me fix it

2022-04-05 12:20 UTC, jmazzitelli commented
FYI: make sure this specifically makes it into our release notes in case someone in the community is using these /api/status fields for something. We just need to call out the fact we renamed some of these status keys.

2022-04-05 12:24 UTC, jmazzitelli submitted a review, later dismissed
If version.txt is no longer needed or used (this is where we put the UI version string within the server), then there are other things that need to change.

* deploy/get-console.sh - https://github.com/kiali/kiali/blob/v1.48.0/deploy/get-console.sh#L35-L40
* hack/run-kiali.sh - https://github.com/kiali/kiali/blob/v1.48.0/hack/run-kiali.sh#L470-L474
* deploy/jenkins-ci/Makefile - not sure if we care about this - I think our Jenkins stuff is going away this sprint??

2022-04-05 12:24 UTC, lucasponce commented
> FYI: make sure this specifically makes it into our release notes in case someone in the community is using these /api/status fields for something. We just need to call out the fact we renamed some of these status keys.

Let's have a unified message on the API.
The Kiali API is private, the use of the /api/* endpoints is used for the UI, if some user is using the /api/status or any other endpoint for custom development is something that is not in the project scope to support.

2022-04-07 11:15 UTC, lucasponce approved these changes
Thanks.
It looks correct now:
![image](https://user-images.githubusercontent.com/1662329/162186797-a212d6dc-06fe-4cc6-9fb3-2a5091a3dd07.png)

2022-04-08 06:45 UTC, merged

2022-04-08 06:50 UTC, aljesusg commented
I'll do the backport to 1.48