Cypress:  A test to check kiali help->view debug info
kiali/kiali pull request #4962
Opened 2022-04-14 13:14 UTC by skondkar

Cypress: A cypress test to check kiali help->View Debug info

2022-04-26 12:09 UTC, ScriptingShrimp requested changes
please address required changes, rebase and squash commits. :+1:

2022-04-26 12:09 UTC, ScriptingShrimp commented on frontend/cypress/integration/featureFiles/kiali_help.feature
> +    Then user see console in URL
please refactor this scenario with 
`Given user is at administrator perspective`
for correct usage see
https://github.com/kiali/kiali/blob/bd662370f0950963d1151825915fc9e91db39474/frontend/cypress/integration/featureFiles/kiali_cookie.feature#L6

2022-04-26 12:09 UTC, ScriptingShrimp commented on frontend/cypress/integration/common/kiali_help.ts
> +})
please refactor this code. If you reuse `Given user is at administrator perspective` step correctly (see below), this verbose login code could be deleted. Don't forget to rebase.

2022-05-27 13:18 UTC, lucasponce commented
Is this PR going to progress? It's open for 1.5 months.

2022-06-14 08:27 UTC, lucasponce commented
Closing. If there is activity on this PR, please re-open it, but I'll close old PRs that are 2 months without progress.

2022-06-14 08:27 UTC, closed without merging