loged in user test case
kiali/kiali pull request #4996
Opened 2022-04-25 18:19 UTC by prachiyadav

SMOKE: Log in to kiali and check if correct user is logged in - top right
- https://issues.redhat.com/browse/OSSM-1172

2022-04-27 13:33 UTC, ScriptingShrimp requested changes
please address required changes, rebase and squash commits. +1

2022-04-27 13:33 UTC, ScriptingShrimp commented on frontend/cypress/integration/common/kiali_user.ts
> +    cy.get('.pf-c-dropdown__toggle-text').contains('jenkins')
`contains('jenkins')` please change hard-coded value to a variable defined at top `USERNAME` 

`const USERNAME = Cypress.env('USERNAME') || 'jenkins';` should be defined in this file

2022-04-27 13:33 UTC, ScriptingShrimp commented on frontend/cypress/integration/featureFiles/kiali_user.feature
> +    And user see console in URL
please refactor step `Given user opens base url` with new step `Given user is at administrator perspective` 
for correct usage see
https://github.com/kiali/kiali/blob/bd662370f0950963d1151825915fc9e91db39474/frontend/cypress/integration/featureFiles/kiali_cookie.feature#L6

2022-04-27 13:33 UTC, ScriptingShrimp commented on frontend/cypress/integration/common/kiali_user.ts
> +})
After you refactor feature file, you can delete this steps. Testcase should work the same we as it did before

2022-04-27 13:33 UTC, ScriptingShrimp commented on frontend/cypress/integration/common/kiali_user.ts
> +    cy.get('.pf-c-dropdown__toggle-text').contains('jenkins')
please validate that this testcase is working with `kubeadmin` username

2022-05-27 13:19 UTC, lucasponce commented
What's the status of this PR?

2022-06-14 08:28 UTC, lucasponce commented
Closing. If there is activity on this PR, please re-open it. I'll close PRs within 2 months without activity.

2022-06-14 08:28 UTC, closed without merging