Outbound traffic in Overview cards. Added dropdown.
kiali/kiali pull request #5117
Opened 2022-05-25 17:22 UTC by hhovsepy

RFE https://github.com/kiali/kiali/issues/4896

Added Traffic Direction dropdown in Overview toolbar to select Outbound and Inbound traffic to show. Selection triggers reload of Overview items and the traffic with particular direction.

Added cypress tests.

![Screenshot from 2022-05-25 18-04-08](https://user-images.githubusercontent.com/604313/170324884-e877f278-d63a-432e-9330-043d68d19235.png)

2022-05-26 18:16 UTC, leandroberetta reviewed
@hhovsepy very nice addition to the overview page. 

Everything LGTM, only some minor comments, one is below and the other is an aesthetic comment:

![overview_in_out_traffic](https://user-images.githubusercontent.com/1286393/170550404-1dedbf55-5c21-458d-b387-d9793cf8c687.png)

I guess we need more space between the chart and the "ops" axis label, but also following Andrew's comment on the issue, more space separating the section above.

2022-05-26 18:16 UTC, leandroberetta commented on frontend/cypress/integration/common/overview.ts
> +When(`user selects {string} traffic duration`, (duration) => {
Typo, I guess it should be direction.

I guess we can add the type to the parameter? (direction: string)

2022-05-27 08:14 UTC, lucasponce commented
Minor:
![image](https://user-images.githubusercontent.com/1662329/170659476-5075ff8e-ffd4-42fb-81a4-709cd8062293.png)

"Traffic direction" -> "Traffic"

I think that in the chart we use the "inbound/outbound traffic" then the text can be shorter, which would help to not have a very large populated toolbar

2022-05-27 08:55 UTC, lucasponce commented
Some note, I'm reviewing the graph vs the overview to check that information is synced:
![image](https://user-images.githubusercontent.com/1662329/170666022-e55c7a86-b69e-4b01-90f4-b512c4ead796.png)

Queries used are correct:
![image](https://user-images.githubusercontent.com/1662329/170666306-722c46ef-73ec-46a6-8fa7-977bd28a6dc9.png)

But I saw some gap in the Graph sidebar, "total" is populated:
![image](https://user-images.githubusercontent.com/1662329/170666477-748a1e2a-9644-4d00-bae4-b60624bf5f34.png)


But, "inbound" and "outbound" are empty:
![image](https://user-images.githubusercontent.com/1662329/170666601-b5b1e7ab-f996-45c4-85e7-5c9ed6755541.png)
![image](https://user-images.githubusercontent.com/1662329/170666639-27e36660-8713-4665-89cd-855b7f9749e0.png)

It sounds a regression for @jshaughn but it's out of the scope of this PR, just leaving the comment here.

2022-05-27 08:55 UTC, lucasponce requested changes
LGTM
A minor suggestion to "shorten" the name to avoid a populated toolbar, but the work looks good.

2022-05-27 10:39 UTC, hhovsepy commented
Have updated the paddings and the toolbar text.

2022-05-27 10:45 UTC, hhovsepy commented
"MeshConfig.OutboundTrafficPolicy.Mode" flag will be added in a scope of different PR.

2022-05-27 10:45 UTC, hhovsepy commented
![Screenshot from 2022-05-27 12-45-37](https://user-images.githubusercontent.com/604313/170685089-0b1e7441-1783-4727-a57d-b65aba145636.png)

2022-05-27 11:08 UTC, lucasponce approved these changes

2022-05-27 11:08 UTC, merged

2022-05-27 13:07 UTC, jshaughn commented
@lucasponce , I'll look at that graph side panel.  One comment for you and @hhovsepy re: this PR:  Perhaps the new dropdown should be disabled when using small cards, because they have no graph?

2022-05-27 13:18 UTC, jshaughn commented
> It sounds a regression for @jshaughn but it's out of the scope of this PR, just leaving the comment here.

Actually this is working as expected.  There is no `Incoming` traffic into the selected namespace, and no outgoing traffic from the namespace.  The total reflects the traffic within the namespace.

2022-05-27 13:26 UTC, lucasponce commented
Then this picture:
![image](https://user-images.githubusercontent.com/1662329/170708207-3036afb2-2bf6-4eb8-bbf9-c27c51ee7a90.png)

The "total" is the sum of the inbound of the workload and the outbound of the workloads, but it doesn't necessarily mean out of the namespace.

am I right?

2022-05-27 14:00 UTC, jshaughn commented
I believe the numbers and sparklines are all as intended.  The reason it's confusing is that "Inbound" and "Outbound" have some context-specific semantics, and there is currently no tooltip or other help to actually explain what it means in the different places.  

For example, for the full graph side-panel, "Inbound" is defined as traffic originating from a traffic source, i.e. the traffic flowing into the graph.  This makes sense.   For the namespace side-panel "Inbound" means traffic entering the namespace from outside the namesapce.  This also makes sense.  "Total" in all cases (I think) means all of the traffic for the object under observation.

Note that the community has never really complained, so I'm not sure they care, or look carefully at some of this stuff.  And I think we should prioritize changes accordingly (meaning I'm not in favor of a lot of work here).

2022-05-27 14:11 UTC, lucasponce commented
> Actually this is working as expected. There is no Incoming traffic into the selected namespace and no Outgoing traffic from the namespace. The total reflects the traffic within the namespace.

I was thinking more of a minor tooltip to explain this, here and potentially on the overview page. The queries look right but I think that contextual information should deserve some notes.