Hopefully a better one
kiali/kiali pull request #5325
Opened 2022-07-21 14:34 UTC by matejnesuta

Just a little suit for my PR involving logging in, visiting the graph page, typing something random into the find form and then expecting an error message to pop up.

Far from being perfect, but it is what it is.

(accidentally pushed some junk last time, now it should be alright)

2022-07-21 14:49 UTC, jmazzitelli commented
Also, please provide a better title for this PR.. "Hopefully a better one" explains nothing about the PR.

2022-07-21 15:10 UTC, matejnesuta commented
I was assigned to do my first PR as an intern in RH, so this is it. I apologize for the inconvenience and will make sure to do it properly the next time.

2022-07-21 15:17 UTC, ScriptingShrimp requested changes
Please address requested changes above.

2022-07-22 09:59 UTC, matejnesuta commented on frontend/cypress/integration/featureFiles/mnesuta_pr.feature
> +    And user graphs "bookinfo" namespaces
https://github.com/kiali/kiali/issues/5329

Due to this, it is not possible to do a reasonable smoke test atm.

2022-07-22 10:04 UTC, ScriptingShrimp commented on frontend/cypress/integration/featureFiles/mnesuta_pr.feature
> +    And user graphs "bookinfo" namespaces
@jmazzitelli can you please verify https://github.com/kiali/kiali/issues/5329 ?

2022-07-28 11:55 UTC, ScriptingShrimp commented on frontend/cypress/integration/common/mnesuta_pr.ts
> +})
please add newline

2022-07-28 13:32 UTC, ScriptingShrimp submitted a review, later dismissed
LGTM

2022-07-28 13:46 UTC, jmazzitelli requested changes
The names of these files should change. "mnesuta_pr" ?? We don't name files with user names or with "pr"... the names of the files should briefly describe the test (its the title of the test, not the user who created it... and obviously its created via a PR so no need to put `_pr` in the name).

2022-07-28 15:46 UTC, jmazzitelli commented
Is this all this test is going to do? Test that find/hide produces an error message when there is no graph nodes? Or is more going to be added to this? If this is all, then we should just add this little test in an existing cypress test rather than create another feature test suite. If more will be added later, then we can keep this test called "graph_smoke" and just add more smoke-testing to it. But I just want to make sure we aren't really committing to master a feature test suite with this little test as the only thing it will do.

2022-07-28 16:34 UTC, matejnesuta commented
Well, I was assigned to do one simple test for my first PR, so I came up with this. Unfortunately, I am not able to answer your question and @ScriptingShrimp is offline for the rest of the day, but I hope he'll be able to answer you tomorrow.

2022-07-28 16:50 UTC, jshaughn commented
There is already a `graph_find_hide.feature` file.  If you are going to add a test in this area I would suggest incorporating it into the existing test feature.

2022-08-02 10:05 UTC, ScriptingShrimp approved these changes
LGTM, rerunning pipeline after rebase

2022-08-02 11:54 UTC, merged