Update testing demos to be compatible with OpenShift 4.11
kiali/kiali pull request #5397
Opened 2022-08-19 16:03 UTC by josunect

- Moved the creation of the scc before apply any yaml in the namespace to avoid warnings. 
- Added scc for the user. Related: https://istio.io/latest/docs/setup/platform-setup/openshift/ (The Istio sidecar injected into each application pod runs with user ID 1337, which is not allowed by default in OpenShift. )

TODO: Need to be tested in previous versions (4.10 compatible)

Fixes #5394

2022-08-22 07:55 UTC, josunect commented
Most workloads can be made compliant by the following simple changes: https://github.com/openshift/cluster-openshift-controller-manager-operator/pull/240/files (random simple example)

2022-08-23 16:28 UTC, josunect commented
Tested the solution: 
 https://github.com/openshift/cluster-openshift-controller-manager-operator/pull/240/files
But still the pods are not able to start, with the following error: "unable to validate against any security context constraint"

2022-08-31 15:31 UTC, jmazzitelli commented
What are the test procedures? (what commands should I run to make sure it all works?)

2022-08-31 15:48 UTC, josunect commented
It would be great to test in 3 different environments:

- minikube
- crc compatible with OpenShift 4.10
- crc compatible with OpenShift 4.11

But at least, I would said crc version compatible with OpenShift 4.11 is required. 

- Istio should be installed. It can be done, using the istio script: 

hack/istio/install-istio-via-istioctl.sh 

- Run the script: 

hack/istio/install-testing-demos.sh 

To validate: 

- The script should not have errors.
- Make sure the pods are up and running. For this, we can either: 
  - Check in the crc dashboard if the pods are running: 
![image](https://user-images.githubusercontent.com/49480155/187721539-b3ab471a-9cad-4d1f-ba73-8e7a80378c68.png)
  - Run kiali and verify that the graphs exist: 
![image](https://user-images.githubusercontent.com/49480155/187721873-12fbc638-ab8b-4404-a393-9273ae8f2322.png)

- The script should have installed 4 namespaces: 
  - bookinfo
  - alpha
  - beta
  - sleep

2022-08-31 16:34 UTC, nrfox commented
Testing on 4.11, the sleep pods never came up for me.

Seeing this failure events in the sleep namespace:
```
oc get events -n sleep                                                                                                                                                                                    Wed 31 Aug 2022 12:31:33 PM EDT
LAST SEEN   TYPE      REASON              OBJECT                        MESSAGE
2m59s       Warning   FailedCreate        replicaset/sleep-5887ccbb67   Error creating: pods "sleep-5887ccbb67-" is forbidden: unable to validate against any security context constraint: [provider "anyuid": Forbidden: not usable by user or serviceaccount, spec.initContainers[0].securityContext.runAsUser: Invalid value: 1337: must be in the ranges: [1000720000, 1000729999], spec.containers[1].securityContext.runAsUser: Invalid value: 1337: must be in the ranges: [1000720000, 1000729999], provider "restricted": Forbidden: not usable by user or serviceaccount, provider "nonroot-v2": Forbidden: not usable by user or serviceaccount, provider "nonroot": Forbidden: not usable by user or serviceaccount, provider "bookinfo-scc": Forbidden: not usable by user or serviceaccount, provider "error-rates-scc": Forbidden: not usable by user or serviceaccount, pod.metadata.annotations[seccomp.security.alpha.kubernetes.io/pod]: Forbidden: seccomp may not be set, pod.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/istio-validation]: Forbidden: seccomp may not be set, pod.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/sleep]: Forbidden: seccomp may not be set, pod.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/istio-proxy]: Forbidden: seccomp may not be set, provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount, provider "machine-api-termination-handler": Forbidden: not usable by user or serviceaccount, provider "hostnetwork-v2": Forbidden: not usable by user or serviceaccount, provider "hostnetwork": Forbidden: not usable by user or serviceaccount, provider "hostaccess": Forbidden: not usable by user or serviceaccount, provider "privileged": Forbidden: not usable by user or serviceaccount]
8m27s       Normal    ScalingReplicaSet   deployment/sleep              Scaled up replica set sleep-5887ccbb67 to 1
```

sleep has its own scc which may or may not be what we want: `sleep-scc`

2022-08-31 16:36 UTC, jmazzitelli commented
Bookinfo traffic generator has this failure - I see this in the replicaset (no pod was able to start):

```
  - lastTransitionTime: "2022-08-31T16:13:46Z"
    message: 'pods "kiali-traffic-generator-" is forbidden: unable to validate against
      any security context constraint: [provider "anyuid": Forbidden: not usable by
      user or serviceaccount, spec.initContainers[0].securityContext.runAsUser: Invalid
      value: 1337: must be in the ranges: [1000770000, 1000779999], spec.containers[1].securityContext.runAsUser:
      Invalid value: 1337: must be in the ranges: [1000770000, 1000779999], provider
      "restricted": Forbidden: not usable by user or serviceaccount, provider "nonroot-v2":
      Forbidden: not usable by user or serviceaccount, provider "nonroot": Forbidden:
      not usable by user or serviceaccount, pod.metadata.annotations[seccomp.security.alpha.kubernetes.io/pod]:
      Forbidden: seccomp may not be set, pod.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/istio-validation]:
      Forbidden: seccomp may not be set, pod.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/kiali-traffic-generator]:
      Forbidden: seccomp may not be set, pod.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/istio-proxy]:
      Forbidden: seccomp may not be set, provider "hostmount-anyuid": Forbidden: not
      usable by user or serviceaccount, provider "machine-api-termination-handler":
      Forbidden: not usable by user or serviceaccount, provider "hostnetwork-v2":
      Forbidden: not usable by user or serviceaccount, provider "hostnetwork": Forbidden:
      not usable by user or serviceaccount, provider "hostaccess": Forbidden: not
      usable by user or serviceaccount, provider "node-exporter": Forbidden: not usable
      by user or serviceaccount, provider "privileged": Forbidden: not usable by user
      or serviceaccount]'
```

This is on OpenShift 4.11

2022-08-31 16:36 UTC, jmazzitelli commented
I also get the same error with sleep as @nrfox  does

2022-08-31 16:38 UTC, jmazzitelli commented
Looking at the kiali graph, I do appear to have a good alpha and beta depoyments.

2022-09-01 11:09 UTC, josunect commented
Pushed commit to: 
- Fix error in deploy traffic-generator replicaSet
- Fix error in pod sleep

2022-09-01 13:26 UTC, ScriptingShrimp commented
I did try to execute `./install-testing-demos.sh` against OCP 4.11 with bookinfos installed
- creation of bookinfo namespace get skipped I believe - [full log here](https://gist.github.com/ScriptingShrimp/4c43ba18019c3f0b6e26ff1fdd5dffbc)
- script ends with 1 error :arrow_down: 
```
deployment.apps/x-server unchanged
service/x-server unchanged
deployment.apps/y-server unchanged
service/y-server unchanged
deployment.apps/z-server unchanged
service/z-server unchanged
Installing the 'sleep' app in the 'sleep' namespace...
NAME    DISPLAY NAME   STATUS
sleep                  Active
namespace/sleep not labeled
clusterrole.rbac.authorization.k8s.io/system:openshift:scc:anyuid added: "sleep"
networkattachmentdefinition.k8s.cni.cncf.io/istio-cni unchanged
securitycontextconstraints.security.openshift.io/sleep-scc unchanged
error: the path "/samples/sleep/sleep.yaml" does not exist

$?
bash: 1: command not found...
```

2022-09-01 14:46 UTC, josunect commented
> I did try to execute `./install-testing-demos.sh` against OCP 4.11 with bookinfos installed
> 
>     * creation of bookinfo namespace get skipped I believe - [full log here](https://gist.github.com/ScriptingShrimp/4c43ba18019c3f0b6e26ff1fdd5dffbc)
> 
>     * script ends with 1 error arrow_down
> 
> 
> ```
> deployment.apps/x-server unchanged
> service/x-server unchanged
> deployment.apps/y-server unchanged
> service/y-server unchanged
> deployment.apps/z-server unchanged
> service/z-server unchanged
> Installing the 'sleep' app in the 'sleep' namespace...
> NAME    DISPLAY NAME   STATUS
> sleep                  Active
> namespace/sleep not labeled
> clusterrole.rbac.authorization.k8s.io/system:openshift:scc:anyuid added: "sleep"
> networkattachmentdefinition.k8s.cni.cncf.io/istio-cni unchanged
> securitycontextconstraints.security.openshift.io/sleep-scc unchanged
> error: the path "/samples/sleep/sleep.yaml" does not exist
> 
> $?
> bash: 1: command not found...
> ```

It looks like this should also fail in the previous version - As the error doesn't look related with the changes. 
Anyway, I've sent a commit to fix this. 
Thanks for the review!

2022-09-01 15:00 UTC, jmazzitelli requested changes
just asking to make things consistent with the rest of the code

2022-09-01 15:00 UTC, jmazzitelli commented on hack/istio/install-testing-demos.sh
> +  if [[ "${ISTIO_DIR}" = "" ]]; then
this is trivial, but we should always use the same kind of syntax when possible. This is using what I think is some bash specific syntax (the double brackets) but everywhere else we are using single-bracket notation with the double-equals.

```suggestion
  if [ "${ISTIO_DIR}" == "" ]; then
```

2022-09-01 15:26 UTC, jmazzitelli commented
just got this on minikube:
```
Error from server: admission webhook "validation.istio.io" denied the request: configuration is invalid: empty domain name not allowed
```

I don't know what this affects. There is a sleep pod in "Pending" status - doesn't look like its running. I'm going to try again and see if it happens again. But, @josunect see if you see this on minikube.

2022-09-01 15:33 UTC, josunect commented
> 

Oh! I will check

2022-09-01 15:36 UTC, jmazzitelli commented
This is definitely a problem on minikube. I just started a new, clean minikube and installed Istio, then ran the demo script and got the error. Here is what I did to see the error:

`./hack/k8s-minikube.sh start && ./hack/k8s-minikube.sh istio`

then

`hack/istio/install-testing-demos.sh -c kubectl`

and I get this as the last message printed by the script:

```
Error from server: admission webhook "validation.istio.io" denied the request: configuration is invalid: empty domain name not allowed
```

2022-09-01 15:43 UTC, jmazzitelli commented
The problem appears to be on this line:
```
  ISTIO_INGRESS_HOST=$(${CLIENT_EXE} get cm -n bookinfo traffic-generator-config -o jsonpath='{.data.route}' | sed 's|.*//\([^\:]*\).*/.*|\1|')
```

2022-09-01 15:45 UTC, ScriptingShrimp commented
for me passed on CRC 4.10 and OCP 4.11

2022-09-01 15:47 UTC, jmazzitelli commented
@josunect I know what the problem is. We need to be able to pass in the minikube profile name. This is my minikube I use for my internal "CI" nightly testing, so I name the minikube profile "ci" (it is NOT the default `minikube`). That breaks this script. We need to be able to pass this in: https://github.com/kiali/kiali/blob/v1.55.0/hack/istio/install-bookinfo-demo.sh#L82-L85

2022-09-01 18:26 UTC, jmazzitelli commented
```diff
index 8067f9721..c10faed66 100755
--- a/hack/istio/install-testing-demos.sh
+++ b/hack/istio/install-testing-demos.sh
@@ -61,6 +61,9 @@ SCRIPT_DIR="$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)"
 # install the Istio release that was last downloaded (that's the -t option to ls)
 ISTIO_DIR=$(ls -dt1 ${SCRIPT_DIR}/../../_output/istio-* | head -n1)
 
+# only used when cluster is minikube
+MINIKUBE_PROFILE="minikube"
+
 : ${CLIENT_EXE:=oc}
 : ${DELETE_DEMOS:=false}
 
@@ -75,11 +78,16 @@ while [ $# -gt 0 ]; do
       DELETE_DEMOS="$2"
       shift;shift
       ;;
+    -mp|--minikube-profile)
+      MINIKUBE_PROFILE="$2"
+      shift;shift
+      ;;
     -h|--help)
       cat <<HELPMSG
 Valid command line arguments:
   -c|--client: either 'oc' or 'kubectl'
   -d|--delete: if 'true' demos will be deleted; otherwise, they will be installed
+  -mp|--minikube-profile <name>: If using minikube, this is the minikube profile name (default: minikube).
   -h|--help: this text
 HELPMSG
       exit 1
@@ -121,7 +129,7 @@ if [ "${DELETE_DEMOS}" != "true" ]; then
     "${SCRIPT_DIR}/install-error-rates-demo.sh"
   else
     echo "Deploying bookinfo demo..."
-    "${SCRIPT_DIR}/install-bookinfo-demo.sh" -c kubectl -tg
+    "${SCRIPT_DIR}/install-bookinfo-demo.sh" -c kubectl -mp ${MINIKUBE_PROFILE} -tg
     echo "Deploying error rates demo..."
     "${SCRIPT_DIR}/install-error-rates-demo.sh" -c kubectl
   fi
@@ -162,4 +170,4 @@ else
     echo "Deleting error rates demo..."
     "${SCRIPT_DIR}/install-error-rates-demo.sh" --delete true -c kubectl
   fi
```

2022-09-01 20:11 UTC, jmazzitelli commented
My PR to this PR also fixes the travel demo script too.

2022-09-02 12:53 UTC, jmazzitelli approved these changes

2022-09-02 12:55 UTC, merged

2022-09-02 15:38 UTC, ScriptingShrimp commented
Tested all three install scripts on OCP 4.11 with no problems.