Relax missing label wording
kiali/kiali pull request #5419
Opened 2022-08-30 07:42 UTC by josunect

Fixes #5368 

![image](https://user-images.githubusercontent.com/49480155/187379157-2012bb12-0f62-41de-a29c-6c715a662a56.png)

2022-08-30 13:07 UTC, jshaughn requested changes
@josunect The change is good, but let's also update that second line.  Thanks.

2022-08-30 13:07 UTC, jshaughn commented on frontend/src/components/MissingLabel/MissingLabel.tsx
>          <div>Missing labels will impact in the telemetry collected by the Istio proxy.</div>
```suggestion
        <div>Missing labels may impact telemetry reported by the Istio proxy.</div>
```

2022-09-09 14:31 UTC, josunect commented
![image](https://user-images.githubusercontent.com/49480155/189374106-fce1aa98-eeb0-40ed-8352-0d063c0a770b.png)

2022-09-09 15:19 UTC, jshaughn approved these changes
LGTM

2022-09-13 10:47 UTC, merged