[Cypress] Mismatched node type graph fix testing
kiali/kiali pull request #5434
Opened 2022-09-05 12:31 UTC by matejnesuta

This is a little test case related [to this issue fix](https://github.com/kiali/kiali-ui/pull/2328) from 1.48.  

It toggles the node graph on the services/<detail>/ page and then checks that the graph type dropdown on the top of the page is disabled.

2022-09-06 16:34 UTC, josunect approved these changes
Tested and works as expected. 
Code looks good. 

Thanks!

2022-09-07 11:01 UTC, matejnesuta commented on frontend/cypress/integration/common/service_details.ts
> +    cy.contains(title).should('exist');
I replaced the `cy.wait(1000);` line with something hopefully more sensible.

2022-09-08 14:52 UTC, nrfox commented
@matejnesuta there's a CI failure for the newly added test if you wouldn't mind looking into it: https://github.com/kiali/kiali/runs/8243955353?check_suite_focus=true

2022-09-08 15:47 UTC, matejnesuta commented
Looking at the screenshot right now. The page seems fine. My first guess is that the `'exist'` should be replaced with `'be.visible'`. @nrfox

2022-09-08 16:29 UTC, matejnesuta commented
And it failed again. I will investigate it tomorrow I think.

2022-09-09 14:25 UTC, josunect commented
If you see the image from the failing test: 
https://github.com/kiali/kiali/suites/8198803432/artifacts/357005649

The node link is disabled because there is no service selected (No namespace is selected). 
When I run this test locally I don't have that error.

2022-09-09 14:53 UTC, matejnesuta commented
> 

You are right. Didn't see that yesterday. The namespace is selected, but it takes time to load the graph. That's why it failed probably.
The thing is, the tests are passing locally for me as well, so it's hard for me to predict what's gonna flake.

2022-09-09 16:05 UTC, josunect commented
> Added a codition that the mini-graph should be visible before the click happens. I hope everything will be good now.

I think this is more related to the order in which the steps are performed. 
If you notice, the file is expecting to have an ordered list of steps (Given, when, then, and, ...). But when is breaking the sequence.

2022-09-09 16:49 UTC, matejnesuta commented
>I think this is more related to the order in which the steps are performed. If you notice, the file is expecting to have an ordered list of steps (Given, when, then, and, ...). But when is breaking the sequence.

I don't think so. The preproccessor doesn't care about the gherkin keywords. For example, this gherkin line ( `But user sees a minigraph`) can be translated with this typescript `Then('user sees a minigraph', () => { ... });`, even though the keywords are different and it doesn't make much sense visually.

2022-09-26 12:17 UTC, josunect requested changes
So, looking at the code, the "Show Node Graph" link action is using data from the xhr call to create the url params. It looks like it haven't finished (From the screenshot). So, I will add a condition to wait for the xhr call before perform the click action in that link.
The xhr call: 

/namespaces/{namespace}/services/{service} services serviceDetails

As an example: 

http://localhost:3000/api/namespaces/bookinfo/services/productpage?validate=true

![image](https://user-images.githubusercontent.com/49480155/192273819-13afa65b-f8b5-4548-b7a1-61a7ac39a2fc.png)

![image](https://user-images.githubusercontent.com/49480155/192273931-3528a8c3-1902-4064-ab08-5e9d70b11398.png)

That could explain why this test is working in my environment (Is pretty quick), but not in CI.

![image](https://user-images.githubusercontent.com/49480155/192268798-462e2320-501a-476c-8c34-ad5cd84cb209.png)

2022-10-26 15:52 UTC, matejnesuta commented
I think I fixed the test and it looks like it's passing in the CI.

2022-10-27 08:19 UTC, josunect approved these changes
LGTM

2022-11-02 17:03 UTC, ScriptingShrimp approved these changes
Tested on CRC, all passing, LGTM!

2022-11-02 17:03 UTC, merged