Multicluster - Add cluster params for metrics
kiali/kiali pull request #6131
Opened 2023-05-10 15:55 UTC by josunect

Fix https://github.com/kiali/kiali/issues/6065

2023-05-11 11:41 UTC, josunect commented
Param is not handle in the backend

2023-05-11 15:54 UTC, josunect commented
When we are in multi cluster, send the cluster parameter in the query:

![image](https://github.com/kiali/kiali/assets/49480155/570aa5f6-4de6-44c2-a0f5-305923e67603)

![Uploading image.png…]()

2023-05-16 11:05 UTC, josunect commented
That should include the cluster as part of the metrics query: 

![image](https://github.com/kiali/kiali/assets/49480155/3e5cf10b-2bde-4f9b-881a-e64288195540)

![image](https://github.com/kiali/kiali/assets/49480155/b411f838-d2cc-4496-92bc-67a0d6ed0220)

2023-05-16 14:21 UTC, hhovsepy commented
@josunect can you please add which areas are touched, so to be tested?
Because in Overview page, the metrics queries do not have cluster param:
![Screenshot from 2023-05-16 16-19-50](https://github.com/kiali/kiali/assets/604313/4aaaa4a3-0b33-4621-bb74-620138f8696a)

2023-05-16 16:11 UTC, hhovsepy submitted a review, later dismissed
Looks good, @josunect thank you for the changes, tested locally.

2023-05-16 20:05 UTC, jshaughn requested changes
Initially I thought there was a missing 'cluster' param for the getNamespaceMetrics requests from the full-graph side-panel.  But after thinking about I think it's correct, the full-graph traffic totals ahousl not narrow to a single cluster on those queries, they should show total traffic across clusters, for the namespace (note, this is only relevant for single-namespace graphs, we don't make those queries for multi-namespace graphs).

But, I don't think the same applies to the NamespaceBox side panel.  A NamespaceBox is constrained to a parent cluster, and as such I think the 'cluster' param needs to be added (see SummaryPanelNamespaceBox:553)

2023-05-16 20:05 UTC, jshaughn commented on frontend/src/pages/Graph/SummaryPanelCommon.tsx
> +      return API.getServiceMetrics(nodeData.namespace, nodeData.service!, options);
Are you sure we want to drop the 'cluster' here?  When you have selected a service node it is within a cluster (and within a namespace).  I think we may need to keep this discriminator.

2023-05-16 20:05 UTC, jshaughn commented on frontend/src/services/Api.ts
> +  return newRequest<MetricsStatsResult>(HTTP_VERBS.POST, urls.metricsStats, {}, { queries: queries });
+1 on this change.

2023-05-17 14:37 UTC, merged

2023-09-21 16:12 UTC, matejnesuta commented
Hello. Is this something that could use some back-end testing?