bookinfo installation directly from cypress
kiali/kiali pull request #6242
Opened 2023-06-07 16:27 UTC by matejnesuta

running it against the CI just to know if it works or not

2023-06-08 16:41 UTC, jshaughn reviewed
Hi @matejnesuta , This looks good.  Would it make sense to make this something that is done only once for a feature file?  Does adding the annotation on every Scenario slow things down?

2023-06-08 17:21 UTC, ScriptingShrimp commented
> done only once for a feature file

the hooks for a "feature file" are in `Scenario:` paragraph of feature file. Definitely we can put some of the feature specific codes inhere. We decided to use conditional hook in this case because i.e. bookinfo is not related to the feature, its just a test precondition shared across multiple feature files.

  

> Does adding the annotation on every Scenario slow things down?

Definitively. But the `cy.exec` is executed outside of web browser context, so the slowdown should not be significant (I believe)

2023-06-12 15:34 UTC, ScriptingShrimp commented on frontend/cypress/integration/common/hooks.ts
> +            cy.exec('../hack/istio/install-bookinfo-demo.sh -c kubectl -tg -in istio-system -a amd64');
As we discussed, refactoring of shell scripts will be better approach.

2023-06-12 15:37 UTC, ScriptingShrimp requested changes
we can merge ` @bookinfo-app` annotations in feature files. 

lets refactor bookinfo installation in another PR if you want

2023-06-12 16:14 UTC, matejnesuta commented
I commented out the hook for now, so the annotations can be merged

2023-06-14 11:16 UTC, ScriptingShrimp requested changes
Just remove the comments from `hooks.ts` and LGTM!
Thank you

2023-06-14 11:16 UTC, ScriptingShrimp commented on frontend/cypress/integration/common/hooks.ts
> +// Will be refactored soon
Please roll back the file to its original state. It's not a good practice to commit TODOs and unused code.

2023-06-14 11:26 UTC, matejnesuta commented
I removed the comments as you requested

2023-06-14 12:12 UTC, merged