Bump kube and istio versions
kiali/kiali pull request #6293
Opened 2023-06-21 18:50 UTC by nrfox

2023-06-23 12:37 UTC, ferhoyos requested changes

2023-06-23 12:37 UTC, ferhoyos commented on hack/setup-kind-in-ci.sh
> -if [ "${TARGET_BRANCH}" == "v1.48" ]; then
Kiali v1.48 is used in OSSMC v2.2 and therefore still supported

2024-04-15 07:03 UTC, ferhoyos commented
@nrfox this PR is outdated. I think you can close it.

2024-04-15 15:55 UTC, jshaughn commented
@nrfox Closing, re-open if needed.

2024-04-15 15:55 UTC, closed without merging