L4 Telemetry is barkwards
kiali/kiali pull request #6323
Opened 2023-06-30 12:06 UTC by josunect

Fixes #5822

2023-06-30 23:47 UTC, jshaughn commented
I took a quick look and nice job, I think you found the two places I was talking about when I said, "... in the graph itself we may be able to make a very local change. On the server side, we may also be able to make a local change".  I'll follow up with you on Monday...

2023-07-03 07:48 UTC, josunect commented
> I took a quick look and nice job, I think you found the two places I was talking about when I said, "... in the graph itself we may be able to make a very local change. On the server side, we may also be able to make a local change". I'll follow up with you on Monday...

Sure, thanks @jshaughn . 
I will be reviewing the tests failures.

2023-07-03 16:22 UTC, josunect commented
Example with mTLS enabled: 

![image](https://github.com/kiali/kiali/assets/49480155/ab03416c-3546-4775-8e97-2449c11b118a)

2023-07-05 13:38 UTC, jshaughn requested changes
It looks strange to see the numbers and metrics reversed, but I think it is correct.  I had one question and am requesting just a few changes in comments.

2023-07-05 13:38 UTC, jshaughn commented on graph/api/api_test.go
> +	q6a := `round(sum(rate(istio_tcp_received_bytes_total{reporter="destination",destination_workload_namespace="bookinfo",destination_workload="productpage-v1"} [600s])) by (source_cluster,source_workl
Why did we need to add an extra query?

2023-07-05 13:38 UTC, jshaughn commented on business/metrics_definitions.go
> +		istioName: "istio_tcp_sent_bytes_total", // L4 telemetry is backwards
```suggestion
		istioName: "istio_tcp_sent_bytes_total", // L4 telemetry is backwards, see https://github.com/istio/istio/issues/32399
```

2023-07-05 13:38 UTC, jshaughn commented on business/metrics_definitions.go
> +		istioName: "istio_tcp_received_bytes_total", // L4 telemetry is backwards
```suggestion
		istioName: "istio_tcp_received_bytes_total", // L4 telemetry is backwards, see https://github.com/istio/istio/issues/32399
```

2023-07-05 13:38 UTC, jshaughn commented on graph/telemetry/istio/istio.go
> -			metrics = []string{"istio_tcp_received_bytes_total"}
Above the switch stmt can we add:

// L4 telemetry is backwards, see https://github.com/istio/istio/issues/32399

2023-07-05 15:30 UTC, jshaughn approved these changes
Looks good, nice job!  Assuming the CI passes we can merge.

2023-07-05 17:51 UTC, merged