Add hack script to aggregate traces in MC env
kiali/kiali pull request #6491
Opened 2023-08-17 14:36 UTC by nrfox

Aggregates tracing in local/testing multicluster environments.

2023-08-17 18:20 UTC, ScriptingShrimp commented
> Aggregates tracing in local/testing multicluster environments.

just wondering why is good to have traces aggregated in the one of the instances

2023-08-17 18:40 UTC, nrfox commented
> > Aggregates tracing in local/testing multicluster environments.
> 
> just wondering why is good to have traces aggregated in the one of the instances

Kiali only supports querying traces from a single endpoint. Same with metrics.

2023-08-17 20:41 UTC, jmazzitelli requested changes
I didn't run it - but it looks mighty fine. Just change the hardcoded kubectl to using the env var like the rest of the scripts.

2023-08-17 20:41 UTC, jmazzitelli commented on hack/istio/multicluster/setup-tracing.sh
> +# This scripts combines traces from the west cluster into the east cluster by sending traces through the istio-ingressgateway.
```suggestion
# This script combines traces from the west cluster into the east cluster by sending traces through the istio-ingressgateway.
```

2023-08-17 20:41 UTC, jmazzitelli commented on hack/istio/multicluster/setup-tracing.sh
> +ingress_output=$(kubectl get svc -n istio-system --context "${CLUSTER1_CONTEXT}" istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="zipkin-http")]}')
```suggestion
ingress_output=$(${CLIENT_EXE} get svc -n istio-system --context "${CLUSTER1_CONTEXT}" istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="zipkin-http")]}')
```

2023-08-17 20:41 UTC, jmazzitelli commented on hack/istio/multicluster/setup-tracing.sh
> +    kubectl --context "${CLUSTER1_CONTEXT}" patch Service -n istio-system istio-ingressgateway --type=json -p '[{"op": "add", "path": "/spec/ports/-", "value": {"name": "zipkin-http", "port": 9411, "
```suggestion
    ${CLIENT_EXE} --context "${CLUSTER1_CONTEXT}" patch Service -n istio-system istio-ingressgateway --type=json -p '[{"op": "add", "path": "/spec/ports/-", "value": {"name": "zipkin-http", "port": 9411, "protocol": "TCP", "targetPort": 8080}}]'
```

2023-08-17 20:41 UTC, jmazzitelli commented on hack/istio/multicluster/setup-tracing.sh
> +kubectl --context "${CLUSTER1_CONTEXT}" apply -f - <<EOF
```suggestion
${CLIENT_EXE} --context "${CLUSTER1_CONTEXT}" apply -f - <<EOF
```

2023-08-17 20:41 UTC, jmazzitelli commented on hack/istio/multicluster/setup-tracing.sh
> +kubectl --context "${CLUSTER1_CONTEXT}" apply -f - <<EOF
```suggestion
${CLIENT_EXE} --context "${CLUSTER1_CONTEXT}" apply -f - <<EOF
```

2023-08-17 20:41 UTC, jmazzitelli commented on hack/istio/multicluster/setup-tracing.sh
> +ISTIO_INGRESS_IP=$(kubectl --context "${CLUSTER1_CONTEXT}" get service -n istio-system istio-ingressgateway -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
```suggestion
ISTIO_INGRESS_IP=$(${CLIENT_EXE} --context "${CLUSTER1_CONTEXT}" get service -n istio-system istio-ingressgateway -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
```

2023-08-17 20:41 UTC, jmazzitelli commented on hack/istio/multicluster/setup-tracing.sh
> +kubectl --context "${CLUSTER2_CONTEXT}" apply -f - <<EOF
```suggestion
${CLIENT_EXE} --context "${CLUSTER2_CONTEXT}" apply -f - <<EOF
```

2023-08-21 13:28 UTC, jmazzitelli approved these changes

2023-08-21 16:43 UTC, merged