Gherkin scenarios for list pages
kiali/kiali pull request #6513
Opened 2023-08-23 15:32 UTC by matejnesuta

Related to #6474.

I have also updated existing tests with some additional checks.

2023-08-25 13:47 UTC, ScriptingShrimp requested changes
I think I could resolve conflicts better. Nitpicked few tags, otherwise LGTM

2023-08-25 13:47 UTC, ScriptingShrimp commented on frontend/cypress/integration/featureFiles/services.feature
> +  @services-page
we can omit this tag in favor of `@services` at the  first line

2023-08-25 13:47 UTC, ScriptingShrimp commented on frontend/cypress/integration/featureFiles/services.feature
> +  @services-page
we can omit this tag in favor of `@services` at the  first line

2023-08-25 13:47 UTC, ScriptingShrimp commented on frontend/cypress/integration/featureFiles/workloads.feature
> +  @workloads-page
we can omit this tag in favor of `@workloads` at the  first line

2023-08-25 13:47 UTC, ScriptingShrimp commented on frontend/cypress/integration/featureFiles/workloads.feature
> +  @workloads-page
we can omit this tag in favor of `@workloads` at the first line

2023-09-04 16:32 UTC, hhovsepy approved these changes
lgtm

2023-09-04 16:39 UTC, merged