[hack] script to set up openshift prometheus for istio monitoring
kiali/kiali pull request #6822
Opened 2023-11-03 21:14 UTC by jmazzitelli

2023-11-08 23:35 UTC, jmazzitelli commented
I had everything installed first (Istio, Kiali, Bookinfo) and all working and graph in Kiali looks normal.
I then ran the script in this PR and it ran successfully. So it all appears to be configured as documented here: https://docs.openshift.com/container-platform/4.14/service_mesh/v2x/ossm-observability.html#ossm-integrating-with-user-workload-monitoring_observability

However, it doesn't work. Kiali UI shows errors in productpage workload and the graph doesn't show things correctly. So I don't know what is wrong.

![image](https://github.com/kiali/kiali/assets/2029470/9b6bc2a0-ba0a-45f7-ac5f-7e2a7dec7ed7)

2023-11-09 14:56 UTC, jmazzitelli commented
How I'm attempting to see this work:
1. Start OpenShift cluster via CRC, enabling cluster monitoring: `./hack/crc-openshift.sh --enable-cluster-monitoring true start`
2. Install Istio: `hack/istio/install-istio-via-istioctl.sh -c oc`
3. Install Bookinfo: `hack/istio/install-bookinfo-demo.sh -c oc -tg`
4. Build/Push/Deploy Kiali: `make build build-ui cluster-push operator-create kiali-create`

At this point, everything should look normal. Kiali should see the graph of bookinfo traffic because all the telemetry is being scraped and stored by the Prometheus addon that was installed when the hack script installed Istio.

Now we want to tell OpenShift Prometheus to start scraping our mesh telemetry, and we want to tell Kiali to query that OpenShift Prometheus rather than the Prometheus addon:

5. `hack/use-openshift-prometheus.sh -n bookinfo`

This __should_ work, if everything has been configured correctly. (as of 11/9/2023, things aren't working).

2023-11-09 17:46 UTC, jmazzitelli commented
Note: this will not work with Ambient. We would need to add PodMonitor or ServiceMonitor to the ztunnel and waypoint proxies. I will ignore that for now and just support sidecars.

2023-11-09 19:01 UTC, jmazzitelli commented
This is ready for review. Everything works nicely now.

2023-11-10 12:05 UTC, josunect approved these changes
Followed the testing procedures and works as expected. 

Metrics in crc: 

![image](https://github.com/kiali/kiali/assets/49480155/70790131-2e35-4216-9963-ed23a22913c7)

Targets:

![image](https://github.com/kiali/kiali/assets/49480155/a4252fef-ddb9-48fa-91fe-eba4a0957b7d)

![image](https://github.com/kiali/kiali/assets/49480155/8cb67705-90e9-4fe2-85d8-2a7025f749df)

Kiali bookinfo graph: 

![image](https://github.com/kiali/kiali/assets/49480155/d6066978-54e6-46eb-85e5-80ec90ea9e8d)

2023-11-10 12:07 UTC, josunect requested changes
I went too fast. 

Just a minor thing but, when I run with -d, I got: 

`hack/use-openshift-prometheus.sh -d`
hack/use-openshift-prometheus.sh: line 24: $2: unbound variable

2023-11-10 12:16 UTC, merged