[OSSM-5306][OSSM-5307] Add building tests images into pipeline
kiali/kiali pull request #6938
Opened 2023-12-08 09:14 UTC by mkralik3

**Describe the change**

Adding a workflow (`tests-images-creator.yml`) for building and pushing integration and cypress test images. The workflow can be run from a different workflow (e.g. as a part of nightly or release process) or manually (e.g. for manually rebuilding a particular tag).

1. The workflow is called from a `nightly` job, so with every nightly job, the integration, and Cypress test images are updated under the latest `tag` in Quay.

2 In addition, the workflow is called whenever a new tag is created (e.g. after release) by `release-tests-images.yml`. In that case, the new integration and cypress test images are created in Quay under the released tag version, e.g. `1.65.12`. Also, the images under the tag `1.65` are updated to point to the latest Z version (other words, the X.Y tag will contain always the latest X.Y.Z released version).

**Issue reference**
Ref:
https://issues.redhat.com/browse/OSSM-5306
https://issues.redhat.com/browse/OSSM-5307

**Examples**

- Manual trigger with `manual` tag: https://github.com/mkralik3/kiali/actions/runs/7132147488
- Nightly pipeline with building tests images: https://github.com/mkralik3/kiali/actions/runs/7132167958
- After tag creation: https://github.com/mkralik3/kiali/actions/workflows/release-tests-images.yml (I have created two tags, `v1.65.44` and `v1.65.45`. So after that, the Quay repo contains `v1.65.44`, `v1.65.4`, `v1.65` images)

**Additional info**
I will backport this to the master and other necessary branches[which are maintained]. This needs to be backported as well https://github.com/kiali/kiali/commit/887d4100a4ef5a37664823e346ee84593009e9bb that is why firstly I want to add all these changes to 1.65 which is ready for it

2023-12-13 07:25 UTC, mkralik3 commented
Ready for review. The description was updated to reflect recent changes.

2023-12-19 01:17 UTC, jshaughn requested changes
@mkralik3 Good work, Everything looks fine.  My only comments are just cosmetic.  In English things will be a little more clear by removing some unnecessary plurals.  I made a few suggestions in the comments.  Also, in the file names please change "tests-" to "test-", thanks!

test-images-creator.yml
test-images-release.yml
test-images-update-latest.yml

2023-12-19 14:10 UTC, mkralik3 commented
@jshaughn Thanks. Updated.

2023-12-19 15:27 UTC, jshaughn approved these changes
Looks good!

2024-01-05 02:08 UTC, ScriptingShrimp approved these changes
LGTM.
I can see images in quay. Not sure how to run workflows before merge, but will try right after.

@mkralik3 please feel free to close the Jiras

2024-01-05 02:08 UTC, ScriptingShrimp commented on .github/workflows/test-images-update-latest.yml
> +    paths:
nothing is missing  here :+1:

2024-01-05 02:09 UTC, merged

2024-01-05 02:14 UTC, ScriptingShrimp commented
@mkralik3 can we discuss following? 
> I will backport this to the master and other necessary branches[which are maintained]. This needs to be backported as well (+ update cypress docker file), that is why firstly I want to add all these changes to 1.65 which is ready for it.

2024-01-05 08:46 UTC, mkralik3 commented
@ScriptingShrimp Since this is going only into v1.65, it will be running only when a new v1.65 tag is created there. To test manual workflow (see it in the actions page), you need to merge the [backport](https://github.com/kiali/kiali/pull/6978) into the master. Since this is done, I have set backports pull requests to `master` and `v1.73` as ready.