Added new target for integration-tests-only
kiali/kiali pull request #7959
Opened 2024-11-25 15:20 UTC by hhovsepy

Added a new target for using in Jenkins pipelines.

2024-11-25 15:25 UTC, mkralik3 submitted a review, later dismissed

2024-11-25 15:58 UTC, nrfox requested changes

2024-11-26 11:33 UTC, mkralik3 approved these changes

2024-11-26 14:50 UTC, hhovsepy commented
@nrfox have removed the odd targets

2024-11-26 14:58 UTC, nrfox approved these changes

2024-11-26 15:00 UTC, merged